plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
}
version = project.mod_version ?: "1.0.0"
group = project.maven_group ?: "net.topuclient"

repositories {
    mavenCentral()
    // Add any additional repositories if needed (e.g., Modrinth, Terra, etc.)
}

dependencies {
    // To change versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API (uncomment if your mod requires fabric api)
    // modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Kotlin language support for Fabric
    modImplementation "net.fabricmc:fabric-language-kotlin:${project.kotlin_loader_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    // Loom will automatically attach sources jars to the generated dev jars
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}
